[package]
name = "geekapk_emailservice"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[dependencies]
sendgrid = "0.6"
redis = "0.8"
threadpool = "1.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
